### ISSUE TITLE
Error preg_match_all(): Compilation failed: lookbehind assertion is not fixed length at offset 105

### ISSUE THREAD

**Issue by acondura** [N-Parsons/grav-plugin-embed-fontawesome#2]
Every time I enabled the updated 0.1.6 version of the plugin I get:

preg_match_all(): Compilation failed: lookbehind assertion is not fixed length at offset 105

<img width="1909" alt="Screenshot 2020-05-31 at 19 30 13" src="https://user-images.githubusercontent.com/1694890/83357523-8b318180-a375-11ea-8b2a-db0e35ae0d93.png">

**Comment by N-Parsons** [comment]
Hi @acondura, could you let me know which version of PHP you are using?

**Comment by acondura** [comment]
I'm on 7.2.27.

**Comment by N-Parsons** [comment]
Thanks for the bug report, @acondura.

This should now be fixed in v0.1.7, but please reopen if you continue to have issues.

**Comment by acondura** [comment]
All good. Thank you for the fast fix!
